#ifndef SHIPNETSIM_H
#define SHIPNETSIM_H

#include <QMainWindow>
#include <any>
#include <osgEarth/ExampleResources>
#include "../components/simulationworker.h"
#include "aboutwindow.h"
#include "gui/windowMangement/processingwindow.h"
#include "settingswindow.h"
#include "../../utils/configurationmanager.h"
#include "utils/utils.h"

QT_BEGIN_NAMESPACE
namespace Ui { class ShipNetSim; }
QT_END_NAMESPACE


// static QString WATER_BOUNDRIES_FILE =
//     ShipNetSimCore::Utils::getDataFile("ne_110m_ocean.shp");
static QList<int> OPTIONAL_SHIPS_TABLE_COLUMNS;

class ShipNetSim : public QMainWindow
{
    Q_OBJECT

    friend class ShipNetSimUI;

public:
    ShipNetSim(QWidget *parent = nullptr);
    ~ShipNetSim();

    /**
     * @brief load default settings
     *
     * @author	Ahmed Aredah
     * @date	7/1/2024
     */
    void loadDefaults();

    /**
     * @brief NeTrainSim::save Default values
     * @param defaults
     * @return
     */
    bool saveDefaults(QStringList defaults);

    /**
    * Displays a warning message with the given text.
    * @param text The text of the warning message to be displayed.
    *
    * @author Ahmed Aredah
    * @date 6/7/2024
    */
    void showWarning(QString text);

    /**
    * Displays a notification with the given text for 3000 millisecond.
    * @param text The text of the notification to be displayed.
    *
    * @author Ahmed Aredah
    * @date 6/7/2024
    */
    void showNotification(QString text);

private:
    /**
     * Sets up the generals
     *
     * @author	Ahmed Aredah
     * @date	2/28/2024
     */
    void setupGenerals();

    /**
    * Sets up the ships table in the UI.
    * This function initializes and populates the ships table with the
    * appropriate columns and data.
    */
    void setupShipsTable();

    /**
     * @brief this function saves the project file on the hard drive.
     * @param saveAs a boolean to either overwrite the previously saved
     * file or create a new one. The default value is to overwrite if the
     * file existed before.
     */
    void saveProjectFile(bool saveAs = false);

    /**
     * @brief load the Project Files to the simulator GUI
     * @param projectFilename the file SNS that has the files address
     *
     * @author Ahmed Aredah
     * @date 6/7/2024
     */
    void loadProjectFiles(QString projectFilename);


    /**
    * Initiates the simulation process.
    * This function starts the simulation based on the selected trains
    * data and updates the UI accordingly.
    */
    void simulate();

    /**
     * @brief get all ships details from the ships table.
     *
     * @return a vector of maps of ships parameters.
     */
    QVector<QMap<QString, QString>> getShipsDataFromTables();

    ShipNetSimCore::GPoint findPortCoords(QString portCode);

    QString convertFromPortCodesToCoords(QString portsString);

    void loadShipsDataToTables(QVector<QMap<QString, QString> > data);

    void setupPage1();

    void setupPage2();

    void setupPage3();

    void showDetailedReport(QString trajectoryFilename);


private slots:
    void on_tabWidget_results_currentChanged(int index);

    /**
     * Slot for clearing the form.
     *
     * @author	Ahmed Aredah
     * @date	6/7/2024
     */
    void clearForm();

    /**
     * Slot for updating the 'visualize trains' combo box.
     *
     * @author	Ahmed Aredah
     * @date	6/7/2024
     */
    void updateCombo_visualizeShips();

    void handleSimulationResultsAvailable(ShipsResults results);

    /**
     * Slot for handling showing the trajectory file in plots.
     *
     * @param trajectoryFile    The trajectory file generated by the simulation.
     *
     * @author	Ahmed Aredah
     * @date	6/7/2024
     */
    void handleViewTrajectoryFile(QString trajectoryFile);


public slots:
    /**
     * Slot for closing the application.
     *
     * @author	Ahmed Aredah
     * @date	6/7/2024
     */
    void closeApplication();


    // /**
    //  * @brief Slot for handling loading the sample project files
    //  *
    //  * @author	Ahmed Aredah
    //  * @date	6/7/2024
    //  */
    // void handleSampleProject();

    /**
     * @brief Slot for pausing the simulation
     */
    void pauseSimulation();

    /**
     * @brief Slot for resuming the simulation
     */
    void resumeSimulation();

    /**
     * @brief slot for terminating the simulation
     */
    void terminateSimulation();

private:
    Ui::ShipNetSim *ui;

    // String to store the project name.
    QString projectName;

    // String to store the network name.
    QString networkName;

    // String to store the author's name.
    QString author;

    // String to store the filename of the project file.
    QString projectFileName;

    // String to store the filename of the trains data.
    QString shipsFilename;

    // Pointer to the AboutWindow object used to display information
    // about the application.
    std::shared_ptr<AboutWindow> aboutWindow = nullptr;

    // Pointer to the settings window used to display and edit settings of
    // the application.
    std::shared_ptr<settingsWindow> theSettingsWindow = nullptr;

    QVector<QPair<QString, QString>> shipsSummaryData;

    ConfigurationManager* configManager;

    // Pointer to the QThread object that is used
    // for running the simulation worker.
    QThread* thread = nullptr;

    // Pointer to the SimulationWorker object used for running
    // the simulation in a separate thread.
    SimulationWorker* worker = nullptr;

    ProcessingWindow* processingWindow = nullptr;

public:
    /**
     * @brief default Browse Path
     */
    QString defaultBrowsePath;

    QString userBrowsePath;

    QList<QString> defaultUnits;

};
#endif // SHIPNETSIM_H
